/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogEditor: typeof import('./../components/BlogEditor/index.vue')['default']
    Components: typeof import('./../views/components/index.vue')['default']
    Dark: typeof import('./../components/DarkMode/dark.vue')['default']
    DarkMode: typeof import('./../components/DarkMode/index.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    'Ep:delete': typeof import('~icons/ep/delete')['default']
    'Ep:edit': typeof import('~icons/ep/edit')['default']
    'Ep:menu': typeof import('~icons/ep/menu')['default']
    'Ep:plus': typeof import('~icons/ep/plus')['default']
    'Ep:promotion': typeof import('~icons/ep/promotion')['default']
    'Ep:reflash': typeof import('~icons/ep/reflash')['default']
    'Ep:refresh': typeof import('~icons/ep/refresh')['default']
    'Ep:search': typeof import('~icons/ep/search')['default']
    'Ep:view': typeof import('~icons/ep/view')['default']
    Game: typeof import('./../layout/components/game.vue')['default']
    GameFooter: typeof import('./../layout/components/GameFooter.vue')['default']
    GameHeader: typeof import('./../layout/components/GameHeader.vue')['default']
    GameMain: typeof import('./../layout/components/GameMain.vue')['default']
    IFrame: typeof import('./../components/iFrame/index.vue')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    Light: typeof import('./../components/DarkMode/light.vue')['default']
    Online: typeof import('./../views/components/game/online.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TankMain: typeof import('../views/components/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
