/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogEditor: typeof import('./../components/BlogEditor/index.vue')['default']
    Components: typeof import('../views/components/TankMain.vue')['default']
    Dark: typeof import('./../components/DarkMode/dark.vue')['default']
    DarkMode: typeof import('./../components/DarkMode/index.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    'Ep:menu': typeof import('~icons/ep/menu')['default']
    Game: typeof import('./../layout/components/game.vue')['default']
    GameFooter: typeof import('./../layout/components/GameFooter.vue')['default']
    GameHeader: typeof import('./../layout/components/GameHeader.vue')['default']
    GameMain: typeof import('./../layout/components/GameMain.vue')['default']
    IFrame: typeof import('./../components/iFrame/index.vue')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    Light: typeof import('./../components/DarkMode/light.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TankMain: typeof import('./../views/components/TankMain.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
